# Custom Exception to break from a loop
class BreakLoopException(Exception):
    pass